CREATE DATABASE Valdivia;
USE Valdivia;
CREATE TABLE persona(RUT INT NOT NULL AUTO_INCREMENT, Nombre VARCHAR(50), Edad INT,PRIMARY KEY(RUT));
CREATE TABLE lugar_de_interes(lugar VARCHAR(50) NOT NULL, descripcion TEXT, categoria VARCHAR(20),latitud FLOAT NOT NULL, longitud FLOAT NOT NULL, Primary key(lugar));
CREATE TABLE desplazarse(RUT INT NOT NULL, fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, latitud FLOAT NOT NULL, longitud FLOAT NOT NULL, FOREIGN KEY fk_RUT(RUT) REFERENCES persona(RUT), PRIMARY KEY (RUT));